name = 'sn-stock-update-dashboard'
main = ".svelte-kit/cloudflare"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "KV"
id = "b350b68ba61a4710aa47095a8e073835"
