name = 'sn-stock-update-workflow'
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-07-04"

[observability]
enabled = true
head_sampling_rate = 1

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "KV"
id = "b350b68ba61a4710aa47095a8e073835"
