name = "sn-stock-update-trigger"
main = "index.ts"
compatibility_date = "2025-07-04"

[vars]
WORKFLOW_URL = "https://sn-stock-update-workflow.michaelcosj.workers.dev"

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 14 * * *"]

[[services]]
binding = "WORKFLOW"
service = "sn-stock-update-workflow"
